sudo: required
language: objective-c
# macOS 10.13 High Sierra
# https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version
osx_image: xcode9.3

before_install:
  # Uninstall existing Homebrew installation.
  - curl -sLO https://raw.githubusercontent.com/Homebrew/install/master/uninstall
  - chmod +x ./uninstall
  - ./uninstall --force
  - sudo rm -rf /usr/local/Homebrew
  - sudo rm -rf /usr/local/Caskroom
  - sudo rm -rf /usr/local/bin/brew

script:
  # Install requirements & run the playbook
  - ./bin/provision
