sudo: required
language: objective-c
# 10.13 (https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version)
osx_image: xcode9.3

before_install:
  # Uninstall existing Homebrew installation.
  - curl -sLO https://raw.githubusercontent.com/Homebrew/install/master/uninstall
  - chmod +x ./uninstall
  - ./uninstall --force
  - sudo rm -rf /usr/local/Homebrew
  - sudo rm -rf /usr/local/Caskroom
  - sudo rm -rf /usr/local/bin/brew

install:
  # Install homebrew
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  # Install Python via homebrew
  - brew install python
  # Install Ansible via pip
  - sudo -H pip install ansible

script:
  # Check playbook syntax
  - ansible-playbook playbook.yml --syntax-check
  # Run the playbook
  - ansible-playbook playbook.yml
