sudo: required
language: objective-c
osx_image: xcode13.4 # macOS Monterey 12.4

before_install:
  # Uninstall existing Homebrew installation.
  - NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
  - chmod +x ./uninstall
  - ./uninstall --force
  - sudo rm -rf /usr/local/Homebrew
  - sudo rm -rf /usr/local/Caskroom
  - sudo rm -rf /usr/local/bin/brew

script:
  # Create a dummy vault password file
  - mkdir -p ~/.ansible && echo "test-password" > ~/.ansible/vault_password
  # Run the Ansible test playbook
  - ./bin/provision -t
