- hosts: all
  connection: local
  tasks:
    - debug: msg="Check if script is being run from the correct directory"
      failed_when: not ansible_env.PWD.endswith('/provision-macos')

- hosts: all
  connection: local
  roles:
    - role: homebrew
      tags: ["homebrew"]
    - role: dotfiles
      tags: ["dotfiles"]
    - role: ssh
      tags: ["ssh"]
    - role: macos
      tags: ["macos"]
    - role: pip
      tags: ["pip"]
    - role: ruby
      tags: ["ruby"]
    - role: node
      tags: ["node"]
    - role: vscode
      tags: ["vscode"]
