- hosts: all
  connection: local
  roles:
    - role: homebrew
      tags: ["homebrew"]
    - role: dotfiles
      tags: ["dotfiles"]
    - role: ssh
      tags: ["ssh"]
    - role: macos
      tags: ["macos"]
    - role: pip
      tags: ["pip"]
    - role: node
      tags: ["node"]
    - role: vscode
      tags: ["vscode"]
