- hosts: all
  connection: local
  tasks:
    - debug: msg="Check if script is being run from the correct directory"
      failed_when: not ansible_env.PWD.endswith('/provision-macos')

- hosts: all
  connection: local
  roles:
    - computername
    - homebrew
    - geerlingguy.dotfiles
