# Creates ~/.vim directories if they don't already exist
- name: Create ~/.vim directories if they don't already exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    recurse: yes
  with_items: "{{ dotfiles_vim_folders }}"

# Clones and symlinks dotfiles
# https://github.com/geerlingguy/ansible-role-dotfiles
- include_role:
    name: geerlingguy.dotfiles
