# Clones and symlinks dotfiles
# https://github.com/geerlingguy/ansible-role-dotfiles
- include_role:
    name: geerlingguy.dotfiles

# Applies a number of macOS default settings, including a theme for Terminal.app
- name: Set macOS defaults
  shell: "{{ dotfiles_home }}/.macos"
