# Symlinks VSCode keybindings and settings files from dotfiles repo
- name: Create VSCode user directory if it doesn't already exist
  file:
    path: "{{ vscode_dest }}"
    state: directory
    mode: 0755
- name: Symlink keybindings and settings files to VSCode user directory
  file:
    src: "{{ vscode_src }}/{{ item }}"
    path: "{{ vscode_dest }}/{{ item }}"
    state: link
  with_items: "{{ vscode_files }}"

# Installs VSCode extensions via the command line (`code`)
# Note: There is currently no support for a config file
- name: Get existing VSCode extensions
  shell: "code --list-extensions"
  register: vscode_existing_extensions
- name: Install VSCode extensions
  shell: "code --install-extension {{ item }}"
  when: item not in vscode_existing_extensions.stdout_lines
  with_items: "{{ vscode_extensions }}"
