# Symlinks VSCode keybindings and settings files
- name: Symlink VSCode keybindings and settings files
  file:
    src: "{{ vscode_src }}/{{ item }}"
    path: "{{ vscode_dest }}/{{ item }}"
    state: link
  become: false
  with_items: "{{ vscode_files }}"

# Installs VSCode extensions via the command line (`code`)
# Note: There is currently no support for a config file
- name: Get existing VSCode extensions
  shell: "code --list-extensions"
  register: vscode_existing_extensions

- name: Install VSCode extensions
  shell: "code --install-extension {{ item }}"
  when: item not in vscode_existing_extensions.stdout_lines
  with_items: "{{ vscode_extensions }}"
