# Applies a number of macOS default settings, including computer name and a theme
# for Terminal.app
# https://github.com/cbracco/dotfiles/blob/master/.macos
- name: Apply macOS default settings, computer name, and a theme for Terminal.app
  shell: "{{ dotfiles_home }}/.macos"
