# Copies ssh-config file to ~/.ssh/config
# Handled separately from dotfiles task because we want to copy and rename this
# file, not symlink it
- name: Create ~/.ssh directory if it doesn't already exist
  file:
    path: "{{ ssh_dir }}"
    state: directory
    mode: 0700
- name: Copy and rename ssh-config file to ~/.ssh/config
  copy:
    src: "{{ ssh_config_src }}"
    dest: "{{ ssh_config_dest }}"

# Decrypts and copies private SSH key file to ~/.ssh
# Skip this step during CI testing
- name: Decrypt private SSH key and copy file to ~/.ssh
  copy:
    src: "{{ ssh_private_key_src }}"
    dest: "{{ ssh_private_key_dest }}"
    mode: 0600
    owner: "{{ ansible_user }}"
  register: id_rsa
  when: test_mode is undefined

# Copies public SSH key file to ~/.ssh
# Skip this step during CI testing
- name: Copy public SSH key file to ~/.ssh
  copy:
    src: "{{ ssh_public_key_src }}"
    dest: "{{ ssh_public_key_dest }}"
    mode: 0600
    owner: "{{ ansible_user }}"
  # when: test_mode is undefined

# Adds id_rsa to ssh-agent
- name: Add id_rsa to ssh-agent
  shell: "ssh-add {{ ssh_key_file }} --apple-use-keychain"
  # when: test_mode is undefined
