# Copies ssh-config file to ~/.ssh/config
# Handled separately from dotfiles task because we want to copy and rename this
# file, not symlink it
- name: Create ~/.ssh directory if it doesn't already exist
  file:
    path: "{{ ssh_dir }}"
    state: directory
    mode: 0700
- name: Copy and rename ssh-config file to ~/.ssh/config
  copy:
    src: "{{ ssh_config_src }}"
    dest: "{{ ssh_config_dest }}"

# Creates an SSH key for the current user if one doesn't exist
# Requires Ansible Vault decryption
- name: Create a 4096-bit SSH key for user in ~/.ssh/id_rsa
  user:
    name: "{{ ansible_ssh_user }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: "{{ ssh_key_file }}"
    ssh_key_comment: "{{ ssh_key_comment }}"
    ssh_key_passphrase: "{{ ssh_key_passphrase|default(omit) }}"

# Adds id_rsa to ssh-agent
- name: Add id_rsa to ssh-agent
  shell: "ssh-add -K {{ ssh_key_file }}"
