- name: Set the computer name
  shell: scutil --set ComputerName {{ computer_name }}
  become: yes
  when: ansible_hostname != computer_name

- name: Set the host name
  shell: scutil --set HostName {{ computer_name }}
  become: yes
  when: ansible_hostname != computer_name

- name: Set the localhost name
  shell: scutil --set LocalHostName {{ computer_name }}
  become: yes
  when: ansible_hostname != computer_name

- name: Set the NetBIOS name
  become: yes
  osx_defaults:
    domain: com.apple.smb.server
    key: NetBIOSName
    type: string
    value: "{{ computer_name }}"
    state: present
