- name: Install homebrew taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  loop: "{{ homebrew_taps }}"
  tags: ['homebrew']

- name: Install homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_packages }}"
  tags: ['homebrew']

- name: Install homebrew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir={{ homebrew_cask_appdir }}"
  loop: "{{ homebrew_cask_packages }}"
  tags: ['homebrew']
