# Installs Node Version Manager (nvm)
# The script clones the nvm repository to ~/.nvm and adds the source line to your
# profile (~/.bash_profile, ~/.zshrc, ~/.profile, or ~/.bashrc)
- name: Install Node Version Manager (nvm)
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

# Installs global npm packages
- name: Install global npm packages
  npm:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('present') }}"
    version: "{{ item.version|default(omit) }}"
    executable: "{{ item.executable|default(omit) }}"
  with_items: "{{ npm_packages }}"
  tags: ["node"]
