# Installs Node Version Manager (nvm)
# The script clones the nvm repository to ~/.nvm and adds the source line to your
# profile (~/.bash_profile, ~/.zshrc, ~/.profile, or ~/.bashrc)
# https://github.com/creationix/nvm
#
# Note: Do not have your NVM_DIR variable set before installing, see
# https://github.com/creationix/nvm/issues/1870
- name: Install Node Version Manager (nvm)
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  args:
    warn: no
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

# Installs latest stable version of node via nvm
- name: Install latest stable version of node via nvm
  shell: which nvm && nvm install node
  args:
    warn: no

# Installs global Node packages
- name: Install global npm packages
  npm:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('present') }}"
    version: "{{ item.version|default(omit) }}"
    executable: "{{ item.executable|default(omit) }}"
    global: "{{ item.global|default('yes') }}"
  loop: "{{ npm_packages }}"
