# Installs global gem packages
- name: Install global gem packages
  pip:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('present') }}"
    version: "{{ item.version|default(omit) }}"
    executable: "{{ item.executable|default(omit) }}"
  with_items: "{{ gem_packages }}"
  tags: ["ruby"]
